### ISSUE TITLE
Add updateItem() method to ToDoList class

### ISSUE THREAD

**Issue by joe-dev-public** [sonianb/fac-to-do-list#13]
- Will need to take array index as parameter.
- Will only be used to toggle done: flag (boolean) for now.

**Comment by sonianb** [comment]
What would be the difference between updateItem() and the already existing markItemDone() method? 
Not sure I understand :/

**Comment by joe-dev-public** [comment]
My mistake - my brain completely missed the markItemDone() method you'd created!

But now I see it, I realise: "markItemDone()" implies that an item cannot be "unmarked" as done. Although it wasn't specified in our user stories, it would be nice to let users toggle whether or not a task is complete (e.g. by checking/unchecking the box next to the item). e.g. a user might click the checkbox by mistake.

"markItemDone()", as a method name, isn't incompatible with this behaviour, but it might be more self-explanatory if it reflected the behaviour.

What do you think?

A separate point: it might be nice to have updateItem() as a more general method, which could theoretically be used to update other properties of the item (e.g. the text). That's not a user story (maybe it could be a stretch goal?), but updateItem() could take two parameters: index and "action", and call other methods depending on what the user wanted to do.
